// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_upstream.proto

package com.adobe.acp.myupstream;

public interface AssetIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:myupstream.AssetId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
