// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_upstream.proto

package com.adobe.acp.myupstream;

/**
 * Protobuf type {@code myupstream.Limit}
 */
public final class Limit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:myupstream.Limit)
    LimitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Limit.newBuilder() to construct.
  private Limit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Limit() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Limit();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.adobe.acp.myupstream.MyUpstreamProto.internal_static_myupstream_Limit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.adobe.acp.myupstream.MyUpstreamProto.internal_static_myupstream_Limit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.adobe.acp.myupstream.Limit.class, com.adobe.acp.myupstream.Limit.Builder.class);
  }

  public static final int NUMOFCHILDREN_FIELD_NUMBER = 1;
  private long numOfChildren_ = 0L;
  /**
   * <code>uint64 numOfChildren = 1;</code>
   * @return The numOfChildren.
   */
  @java.lang.Override
  public long getNumOfChildren() {
    return numOfChildren_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numOfChildren_ != 0L) {
      output.writeUInt64(1, numOfChildren_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numOfChildren_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, numOfChildren_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.adobe.acp.myupstream.Limit)) {
      return super.equals(obj);
    }
    com.adobe.acp.myupstream.Limit other = (com.adobe.acp.myupstream.Limit) obj;

    if (getNumOfChildren()
        != other.getNumOfChildren()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMOFCHILDREN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumOfChildren());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.adobe.acp.myupstream.Limit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.adobe.acp.myupstream.Limit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.adobe.acp.myupstream.Limit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.adobe.acp.myupstream.Limit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.adobe.acp.myupstream.Limit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.adobe.acp.myupstream.Limit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.adobe.acp.myupstream.Limit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.adobe.acp.myupstream.Limit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.adobe.acp.myupstream.Limit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.adobe.acp.myupstream.Limit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.adobe.acp.myupstream.Limit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.adobe.acp.myupstream.Limit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.adobe.acp.myupstream.Limit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code myupstream.Limit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:myupstream.Limit)
      com.adobe.acp.myupstream.LimitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adobe.acp.myupstream.MyUpstreamProto.internal_static_myupstream_Limit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adobe.acp.myupstream.MyUpstreamProto.internal_static_myupstream_Limit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adobe.acp.myupstream.Limit.class, com.adobe.acp.myupstream.Limit.Builder.class);
    }

    // Construct using com.adobe.acp.myupstream.Limit.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      numOfChildren_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.adobe.acp.myupstream.MyUpstreamProto.internal_static_myupstream_Limit_descriptor;
    }

    @java.lang.Override
    public com.adobe.acp.myupstream.Limit getDefaultInstanceForType() {
      return com.adobe.acp.myupstream.Limit.getDefaultInstance();
    }

    @java.lang.Override
    public com.adobe.acp.myupstream.Limit build() {
      com.adobe.acp.myupstream.Limit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.adobe.acp.myupstream.Limit buildPartial() {
      com.adobe.acp.myupstream.Limit result = new com.adobe.acp.myupstream.Limit(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.adobe.acp.myupstream.Limit result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.numOfChildren_ = numOfChildren_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.adobe.acp.myupstream.Limit) {
        return mergeFrom((com.adobe.acp.myupstream.Limit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.adobe.acp.myupstream.Limit other) {
      if (other == com.adobe.acp.myupstream.Limit.getDefaultInstance()) return this;
      if (other.getNumOfChildren() != 0L) {
        setNumOfChildren(other.getNumOfChildren());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              numOfChildren_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long numOfChildren_ ;
    /**
     * <code>uint64 numOfChildren = 1;</code>
     * @return The numOfChildren.
     */
    @java.lang.Override
    public long getNumOfChildren() {
      return numOfChildren_;
    }
    /**
     * <code>uint64 numOfChildren = 1;</code>
     * @param value The numOfChildren to set.
     * @return This builder for chaining.
     */
    public Builder setNumOfChildren(long value) {

      numOfChildren_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 numOfChildren = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumOfChildren() {
      bitField0_ = (bitField0_ & ~0x00000001);
      numOfChildren_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:myupstream.Limit)
  }

  // @@protoc_insertion_point(class_scope:myupstream.Limit)
  private static final com.adobe.acp.myupstream.Limit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.adobe.acp.myupstream.Limit();
  }

  public static com.adobe.acp.myupstream.Limit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Limit>
      PARSER = new com.google.protobuf.AbstractParser<Limit>() {
    @java.lang.Override
    public Limit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Limit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Limit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.adobe.acp.myupstream.Limit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

