// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_upstream.proto

package com.adobe.acp.myupstream;

public interface LimitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:myupstream.Limit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 numOfChildren = 1;</code>
   * @return The numOfChildren.
   */
  long getNumOfChildren();
}
