// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_upstream.proto

package com.adobe.acp.myupstream;

public interface NodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:myupstream.NodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string repositoryId = 1;</code>
   * @return The repositoryId.
   */
  java.lang.String getRepositoryId();
  /**
   * <code>string repositoryId = 1;</code>
   * @return The bytes for repositoryId.
   */
  com.google.protobuf.ByteString
      getRepositoryIdBytes();

  /**
   * <code>string partitionPrefix = 2;</code>
   * @return The partitionPrefix.
   */
  java.lang.String getPartitionPrefix();
  /**
   * <code>string partitionPrefix = 2;</code>
   * @return The bytes for partitionPrefix.
   */
  com.google.protobuf.ByteString
      getPartitionPrefixBytes();

  /**
   * <code>string baseDirectoryId = 3;</code>
   * @return The baseDirectoryId.
   */
  java.lang.String getBaseDirectoryId();
  /**
   * <code>string baseDirectoryId = 3;</code>
   * @return The bytes for baseDirectoryId.
   */
  com.google.protobuf.ByteString
      getBaseDirectoryIdBytes();

  /**
   * <code>string path = 4;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 4;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>.myupstream.NodeInfo.System system = 5;</code>
   * @return Whether the system field is set.
   */
  boolean hasSystem();
  /**
   * <code>.myupstream.NodeInfo.System system = 5;</code>
   * @return The system.
   */
  com.adobe.acp.myupstream.NodeInfo.System getSystem();
  /**
   * <code>.myupstream.NodeInfo.System system = 5;</code>
   */
  com.adobe.acp.myupstream.NodeInfo.SystemOrBuilder getSystemOrBuilder();

  /**
   * <code>string region = 6;</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <code>string region = 6;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <code>.myupstream.NodeInfo.Owner owner = 7;</code>
   * @return Whether the owner field is set.
   */
  boolean hasOwner();
  /**
   * <code>.myupstream.NodeInfo.Owner owner = 7;</code>
   * @return The owner.
   */
  com.adobe.acp.myupstream.NodeInfo.Owner getOwner();
  /**
   * <code>.myupstream.NodeInfo.Owner owner = 7;</code>
   */
  com.adobe.acp.myupstream.NodeInfo.OwnerOrBuilder getOwnerOrBuilder();

  /**
   * <code>string nodeId = 8;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string nodeId = 8;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string name = 9;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 9;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string assetId = 10;</code>
   * @return The assetId.
   */
  java.lang.String getAssetId();
  /**
   * <code>string assetId = 10;</code>
   * @return The bytes for assetId.
   */
  com.google.protobuf.ByteString
      getAssetIdBytes();

  /**
   * <code>string mediaType = 11;</code>
   * @return The mediaType.
   */
  java.lang.String getMediaType();
  /**
   * <code>string mediaType = 11;</code>
   * @return The bytes for mediaType.
   */
  com.google.protobuf.ByteString
      getMediaTypeBytes();

  /**
   * <code>string etag = 12;</code>
   * @return The etag.
   */
  java.lang.String getEtag();
  /**
   * <code>string etag = 12;</code>
   * @return The bytes for etag.
   */
  com.google.protobuf.ByteString
      getEtagBytes();

  /**
   * <code>.google.protobuf.Timestamp createDate = 13;</code>
   * @return Whether the createDate field is set.
   */
  boolean hasCreateDate();
  /**
   * <code>.google.protobuf.Timestamp createDate = 13;</code>
   * @return The createDate.
   */
  com.google.protobuf.Timestamp getCreateDate();
  /**
   * <code>.google.protobuf.Timestamp createDate = 13;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder();

  /**
   * <code>string createdBy = 14;</code>
   * @return The createdBy.
   */
  java.lang.String getCreatedBy();
  /**
   * <code>string createdBy = 14;</code>
   * @return The bytes for createdBy.
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <code>.google.protobuf.Timestamp modifyDate = 15;</code>
   * @return Whether the modifyDate field is set.
   */
  boolean hasModifyDate();
  /**
   * <code>.google.protobuf.Timestamp modifyDate = 15;</code>
   * @return The modifyDate.
   */
  com.google.protobuf.Timestamp getModifyDate();
  /**
   * <code>.google.protobuf.Timestamp modifyDate = 15;</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifyDateOrBuilder();

  /**
   * <code>string modifiedBy = 16;</code>
   * @return The modifiedBy.
   */
  java.lang.String getModifiedBy();
  /**
   * <code>string modifiedBy = 16;</code>
   * @return The bytes for modifiedBy.
   */
  com.google.protobuf.ByteString
      getModifiedByBytes();

  /**
   * <code>.google.protobuf.Timestamp deviceCreateDate = 17;</code>
   * @return Whether the deviceCreateDate field is set.
   */
  boolean hasDeviceCreateDate();
  /**
   * <code>.google.protobuf.Timestamp deviceCreateDate = 17;</code>
   * @return The deviceCreateDate.
   */
  com.google.protobuf.Timestamp getDeviceCreateDate();
  /**
   * <code>.google.protobuf.Timestamp deviceCreateDate = 17;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeviceCreateDateOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp deviceModifyDate = 18;</code>
   * @return Whether the deviceModifyDate field is set.
   */
  boolean hasDeviceModifyDate();
  /**
   * <code>.google.protobuf.Timestamp deviceModifyDate = 18;</code>
   * @return The deviceModifyDate.
   */
  com.google.protobuf.Timestamp getDeviceModifyDate();
  /**
   * <code>.google.protobuf.Timestamp deviceModifyDate = 18;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeviceModifyDateOrBuilder();

  /**
   * <code>string state = 19;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 19;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>.myupstream.NodeInfo.Generations generations = 20;</code>
   * @return Whether the generations field is set.
   */
  boolean hasGenerations();
  /**
   * <code>.myupstream.NodeInfo.Generations generations = 20;</code>
   * @return The generations.
   */
  com.adobe.acp.myupstream.NodeInfo.Generations getGenerations();
  /**
   * <code>.myupstream.NodeInfo.Generations generations = 20;</code>
   */
  com.adobe.acp.myupstream.NodeInfo.GenerationsOrBuilder getGenerationsOrBuilder();

  /**
   * <code>string repoAssetClass = 21;</code>
   * @return The repoAssetClass.
   */
  java.lang.String getRepoAssetClass();
  /**
   * <code>string repoAssetClass = 21;</code>
   * @return The bytes for repoAssetClass.
   */
  com.google.protobuf.ByteString
      getRepoAssetClassBytes();

  /**
   * <code>string nodeType = 22;</code>
   * @return The nodeType.
   */
  java.lang.String getNodeType();
  /**
   * <code>string nodeType = 22;</code>
   * @return The bytes for nodeType.
   */
  com.google.protobuf.ByteString
      getNodeTypeBytes();

  /**
   * <code>.myupstream.NodeInfo._modificationinfo _modificationInfo = 23;</code>
   * @return Whether the modificationInfo field is set.
   */
  boolean hasModificationInfo();
  /**
   * <code>.myupstream.NodeInfo._modificationinfo _modificationInfo = 23;</code>
   * @return The modificationInfo.
   */
  com.adobe.acp.myupstream.NodeInfo._modificationinfo getModificationInfo();
  /**
   * <code>.myupstream.NodeInfo._modificationinfo _modificationInfo = 23;</code>
   */
  com.adobe.acp.myupstream.NodeInfo._modificationinfoOrBuilder getModificationInfoOrBuilder();
}
