// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_upstream.proto

package com.adobe.acp.myupstream;

public interface PageInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:myupstream.PageInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeId = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string nodeId = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string assetId = 3;</code>
   * @return The assetId.
   */
  java.lang.String getAssetId();
  /**
   * <code>string assetId = 3;</code>
   * @return The bytes for assetId.
   */
  com.google.protobuf.ByteString
      getAssetIdBytes();

  /**
   * <code>string mediaType = 4;</code>
   * @return The mediaType.
   */
  java.lang.String getMediaType();
  /**
   * <code>string mediaType = 4;</code>
   * @return The bytes for mediaType.
   */
  com.google.protobuf.ByteString
      getMediaTypeBytes();

  /**
   * <code>string etag = 5;</code>
   * @return The etag.
   */
  java.lang.String getEtag();
  /**
   * <code>string etag = 5;</code>
   * @return The bytes for etag.
   */
  com.google.protobuf.ByteString
      getEtagBytes();

  /**
   * <code>.google.protobuf.Timestamp createDate = 6;</code>
   * @return Whether the createDate field is set.
   */
  boolean hasCreateDate();
  /**
   * <code>.google.protobuf.Timestamp createDate = 6;</code>
   * @return The createDate.
   */
  com.google.protobuf.Timestamp getCreateDate();
  /**
   * <code>.google.protobuf.Timestamp createDate = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder();

  /**
   * <code>string createdBy = 7;</code>
   * @return The createdBy.
   */
  java.lang.String getCreatedBy();
  /**
   * <code>string createdBy = 7;</code>
   * @return The bytes for createdBy.
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <code>.google.protobuf.Timestamp modifyDate = 8;</code>
   * @return Whether the modifyDate field is set.
   */
  boolean hasModifyDate();
  /**
   * <code>.google.protobuf.Timestamp modifyDate = 8;</code>
   * @return The modifyDate.
   */
  com.google.protobuf.Timestamp getModifyDate();
  /**
   * <code>.google.protobuf.Timestamp modifyDate = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifyDateOrBuilder();

  /**
   * <code>string modifiedBy = 9;</code>
   * @return The modifiedBy.
   */
  java.lang.String getModifiedBy();
  /**
   * <code>string modifiedBy = 9;</code>
   * @return The bytes for modifiedBy.
   */
  com.google.protobuf.ByteString
      getModifiedByBytes();

  /**
   * <code>.google.protobuf.Timestamp deviceCreateDate = 10;</code>
   * @return Whether the deviceCreateDate field is set.
   */
  boolean hasDeviceCreateDate();
  /**
   * <code>.google.protobuf.Timestamp deviceCreateDate = 10;</code>
   * @return The deviceCreateDate.
   */
  com.google.protobuf.Timestamp getDeviceCreateDate();
  /**
   * <code>.google.protobuf.Timestamp deviceCreateDate = 10;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeviceCreateDateOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp deviceModifyDate = 11;</code>
   * @return Whether the deviceModifyDate field is set.
   */
  boolean hasDeviceModifyDate();
  /**
   * <code>.google.protobuf.Timestamp deviceModifyDate = 11;</code>
   * @return The deviceModifyDate.
   */
  com.google.protobuf.Timestamp getDeviceModifyDate();
  /**
   * <code>.google.protobuf.Timestamp deviceModifyDate = 11;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeviceModifyDateOrBuilder();

  /**
   * <code>string state = 12;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 12;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>.myupstream.PageInfo.Generations generations = 13;</code>
   * @return Whether the generations field is set.
   */
  boolean hasGenerations();
  /**
   * <code>.myupstream.PageInfo.Generations generations = 13;</code>
   * @return The generations.
   */
  com.adobe.acp.myupstream.PageInfo.Generations getGenerations();
  /**
   * <code>.myupstream.PageInfo.Generations generations = 13;</code>
   */
  com.adobe.acp.myupstream.PageInfo.GenerationsOrBuilder getGenerationsOrBuilder();

  /**
   * <code>string repoAssetClass = 14;</code>
   * @return The repoAssetClass.
   */
  java.lang.String getRepoAssetClass();
  /**
   * <code>string repoAssetClass = 14;</code>
   * @return The bytes for repoAssetClass.
   */
  com.google.protobuf.ByteString
      getRepoAssetClassBytes();

  /**
   * <code>string nodeType = 15;</code>
   * @return The nodeType.
   */
  java.lang.String getNodeType();
  /**
   * <code>string nodeType = 15;</code>
   * @return The bytes for nodeType.
   */
  com.google.protobuf.ByteString
      getNodeTypeBytes();

  /**
   * <code>string repositoryId = 16;</code>
   * @return The repositoryId.
   */
  java.lang.String getRepositoryId();
  /**
   * <code>string repositoryId = 16;</code>
   * @return The bytes for repositoryId.
   */
  com.google.protobuf.ByteString
      getRepositoryIdBytes();

  /**
   * <code>string partitionPrefix = 17;</code>
   * @return The partitionPrefix.
   */
  java.lang.String getPartitionPrefix();
  /**
   * <code>string partitionPrefix = 17;</code>
   * @return The bytes for partitionPrefix.
   */
  com.google.protobuf.ByteString
      getPartitionPrefixBytes();

  /**
   * <code>string baseDirectoryId = 18;</code>
   * @return The baseDirectoryId.
   */
  java.lang.String getBaseDirectoryId();
  /**
   * <code>string baseDirectoryId = 18;</code>
   * @return The bytes for baseDirectoryId.
   */
  com.google.protobuf.ByteString
      getBaseDirectoryIdBytes();

  /**
   * <code>string path = 19;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 19;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>.myupstream.PageInfo.System system = 20;</code>
   * @return Whether the system field is set.
   */
  boolean hasSystem();
  /**
   * <code>.myupstream.PageInfo.System system = 20;</code>
   * @return The system.
   */
  com.adobe.acp.myupstream.PageInfo.System getSystem();
  /**
   * <code>.myupstream.PageInfo.System system = 20;</code>
   */
  com.adobe.acp.myupstream.PageInfo.SystemOrBuilder getSystemOrBuilder();

  /**
   * <code>string region = 21;</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <code>string region = 21;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <code>.myupstream.PageInfo.Owner owner = 22;</code>
   * @return Whether the owner field is set.
   */
  boolean hasOwner();
  /**
   * <code>.myupstream.PageInfo.Owner owner = 22;</code>
   * @return The owner.
   */
  com.adobe.acp.myupstream.PageInfo.Owner getOwner();
  /**
   * <code>.myupstream.PageInfo.Owner owner = 22;</code>
   */
  com.adobe.acp.myupstream.PageInfo.OwnerOrBuilder getOwnerOrBuilder();

  /**
   * <code>repeated .myupstream.PageInfo.Child children = 23;</code>
   */
  java.util.List<com.adobe.acp.myupstream.PageInfo.Child> 
      getChildrenList();
  /**
   * <code>repeated .myupstream.PageInfo.Child children = 23;</code>
   */
  com.adobe.acp.myupstream.PageInfo.Child getChildren(int index);
  /**
   * <code>repeated .myupstream.PageInfo.Child children = 23;</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated .myupstream.PageInfo.Child children = 23;</code>
   */
  java.util.List<? extends com.adobe.acp.myupstream.PageInfo.ChildOrBuilder> 
      getChildrenOrBuilderList();
  /**
   * <code>repeated .myupstream.PageInfo.Child children = 23;</code>
   */
  com.adobe.acp.myupstream.PageInfo.ChildOrBuilder getChildrenOrBuilder(
      int index);

  /**
   * <code>repeated .google.protobuf.Any tags = 24;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getTagsList();
  /**
   * <code>repeated .google.protobuf.Any tags = 24;</code>
   */
  com.google.protobuf.Any getTags(int index);
  /**
   * <code>repeated .google.protobuf.Any tags = 24;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .google.protobuf.Any tags = 24;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getTagsOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any tags = 24;</code>
   */
  com.google.protobuf.AnyOrBuilder getTagsOrBuilder(
      int index);

  /**
   * <code>.myupstream.PageInfo._pagE _page = 25;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.myupstream.PageInfo._pagE _page = 25;</code>
   * @return The page.
   */
  com.adobe.acp.myupstream.PageInfo._pagE getPage();
  /**
   * <code>.myupstream.PageInfo._pagE _page = 25;</code>
   */
  com.adobe.acp.myupstream.PageInfo._pagEOrBuilder getPageOrBuilder();

  /**
   * <code>.myupstream.PageInfo._modificationinfo _modificationInfo = 26;</code>
   * @return Whether the modificationInfo field is set.
   */
  boolean hasModificationInfo();
  /**
   * <code>.myupstream.PageInfo._modificationinfo _modificationInfo = 26;</code>
   * @return The modificationInfo.
   */
  com.adobe.acp.myupstream.PageInfo._modificationinfo getModificationInfo();
  /**
   * <code>.myupstream.PageInfo._modificationinfo _modificationInfo = 26;</code>
   */
  com.adobe.acp.myupstream.PageInfo._modificationinfoOrBuilder getModificationInfoOrBuilder();
}
